/**
 * CREATIVE-01 prototype — adjustment-preset candidate evidence
 * (AUDIT=1).
 *
 * The sign-off sitting owes a starter set of built-in adjustment
 * presets (~8 candidates, slice 2a) judged on before/afters. This
 * audit renders every candidate on the sample card through the real
 * pipeline — adjust before resize (§7), the selection reading the
 * adjusted picture (the ticket's slice-2 engine note) — and reports
 * what each preset does to the picture's tone and to the palette the
 * selector then picks.
 *
 * Evidence for a human decision, not a gate (D139). Artefacts:
 *   bench-reports/creative-01-proto-adjust-<sha>.json
 *   bench-reports/creative-01-proto-adjust-gallery.html
 *
 * PROTOTYPE on branch creative-01-proto: never merged as production
 * source; the signed build re-derives from the ticket.
 */

import { describe, expect, it } from 'vitest';

import { srgbToLab } from '../../src/core/color/convert.ts';
import { log } from '../../src/diagnostics/log.ts';
import type { PermittedSet } from '../../src/core/palette-policy.ts';
import { buildDistribution, selectPalette } from '../../src/core/palette-selection.ts';
import {
  buildStages,
  DEFAULT_DITHER,
  type PipelineConfig,
} from '../../src/core/pipeline/config.ts';
import { runPipeline } from '../../src/core/pipeline/index.ts';
import { resizeStage } from '../../src/core/pipeline/resize.ts';
import { computeStats } from '../../src/core/stats.ts';
import { loadCatalogue } from '../../src/core/thread-catalogue.ts';
import {
  ADJUST_PRESET_CANDIDATES,
  applyAdjustProto,
} from '../../src/core/tone/adjust-proto.ts';
import type { Palette, PixelBuffer } from '../../src/core/types.ts';
import { sampleBuffer } from '../../src/ui/sample.ts';
import { buildIdentity, writeReport } from '../bench/env-node.ts';
import { AUDIT } from './audit.ts';

const GRID = 300;
const COLOR_LIMIT = 8;

/** Mean L* and mean chroma (√(a²+b²)) over opaque cells. */
function toneSummary(buffer: PixelBuffer): { meanL: number; meanChroma: number } {
  const lab = new Float32Array(3);
  let sumL = 0;
  let sumC = 0;
  let n = 0;
  const px = buffer.width * buffer.height;
  for (let p = 0; p < px; p++) {
    const i = p * 4;
    if ((buffer.data[i + 3] ?? 255) === 0) continue;
    srgbToLab(buffer.data[i] ?? 0, buffer.data[i + 1] ?? 0, buffer.data[i + 2] ?? 0, lab, 0);
    sumL += lab[0] ?? 0;
    sumC += Math.hypot(lab[1] ?? 0, lab[2] ?? 0);
    n++;
  }
  return { meanL: n === 0 ? 0 : sumL / n, meanChroma: n === 0 ? 0 : sumC / n };
}

function toBase64(bytes: Uint8ClampedArray): string {
  return Buffer.from(bytes.buffer, bytes.byteOffset, bytes.byteLength).toString('base64');
}

interface GalleryCell {
  label: string;
  buffer: PixelBuffer;
}

function galleryHtml(sections: { title: string; cells: GalleryCell[] }[]): string {
  const blocks = sections
    .map((section) => {
      const cells = section.cells
        .map(
          (cell) =>
            `<figure><canvas data-w="${String(cell.buffer.width)}" data-h="${String(cell.buffer.height)}" data-px="${toBase64(cell.buffer.data)}"></canvas><figcaption>${cell.label}</figcaption></figure>`,
        )
        .join('\n');
      return `<h2>${section.title}</h2>\n<div class="row">${cells}</div>`;
    })
    .join('\n');
  return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><title>CREATIVE-01 adjustment-preset gallery</title>
<style>
body{font:14px/1.4 system-ui;background:#161616;color:#f4f4f4;margin:2rem}
.row{display:flex;flex-wrap:wrap;gap:12px;margin-bottom:2rem}
figure{margin:0}figcaption{text-align:center;padding-top:4px;font-size:12px;max-width:240px}
canvas{image-rendering:pixelated;width:240px;height:240px;background:#333}
h2{font-weight:400;border-bottom:1px solid #555;padding-bottom:4px}
</style></head><body>
<h1>CREATIVE-01 — adjustment-preset candidates, before/afters</h1>
<p>Sample card at 240×240 CSS px, nearest-neighbour. Per candidate:
the adjusted source at grid size, then the render through the default
pipeline (DMC limit 8, Lab, Floyd–Steinberg) with the palette
re-selected from the adjusted picture. Generated by
tests/audits/adjust-presets.audit.test.ts (AUDIT=1). Prototype
evidence, branch creative-01-proto.</p>
${blocks}
<script>
for (const c of document.querySelectorAll('canvas')) {
  const w = +c.dataset.w, h = +c.dataset.h;
  c.width = w; c.height = h;
  const raw = atob(c.dataset.px);
  const px = new Uint8ClampedArray(raw.length);
  for (let i = 0; i < raw.length; i++) px[i] = raw.charCodeAt(i);
  c.getContext('2d').putImageData(new ImageData(px, w, h), 0, 0);
}
</script></body></html>
`;
}

describe.skipIf(!AUDIT)('CREATIVE-01 adjustment-preset candidates (AUDIT=1)', () => {
  it('renders every candidate with a re-selected palette', () => {
    const catalogue = loadCatalogue();
    const dmc = catalogue.threads.filter(
      (t) => t.brandId === 'dmc' && t.status === 'current',
    );
    const permitted: PermittedSet = {
      eligible: dmc,
      locks: [],
      preferred: new Set<string>(),
      unresolved: [],
      conflicts: [],
      ok: true,
    };
    const source = sampleBuffer();
    const baseGrid = resizeStage.backends.ts(source, {
      width: GRID,
      height: GRID,
      mode: 'contain',
    });
    const baseTone = toneSummary(baseGrid);

    const runCandidate = (
      params: (typeof ADJUST_PRESET_CANDIDATES)[number],
    ): {
      adjustedGrid: PixelBuffer;
      output: PixelBuffer;
      palette: Palette;
    } => {
      const adjusted = applyAdjustProto(source, params.params);
      const adjustedGrid = resizeStage.backends.ts(adjusted, {
        width: GRID,
        height: GRID,
        mode: 'contain',
      });
      const palette = selectPalette(
        permitted,
        COLOR_LIMIT,
        buildDistribution(adjustedGrid),
        params.label,
      ).palette;
      const config: PipelineConfig = {
        preset: 'resize-first',
        grid: { width: GRID, height: GRID },
        resizeMode: 'contain',
        palette,
        metric: 'lab',
        dither: { ...DEFAULT_DITHER },
      };
      return { adjustedGrid, output: runPipeline(adjusted, buildStages(config)), palette };
    };

    const sections: { title: string; cells: GalleryCell[] }[] = [];
    const rows = ADJUST_PRESET_CANDIDATES.map((cand) => {
      const { adjustedGrid, output, palette } = runCandidate(cand);
      const tone = toneSummary(adjustedGrid);
      const stats = computeStats(output, palette);
      sections.push({
        title: `${cand.label} — ${cand.basis}`,
        cells: [
          { label: 'adjusted source (grid)', buffer: adjustedGrid },
          { label: 'rendered, palette re-selected', buffer: output },
        ],
      });
      return {
        id: cand.id,
        label: cand.label,
        basis: cand.basis,
        deltaMeanL: tone.meanL - baseTone.meanL,
        deltaMeanChroma: tone.meanChroma - baseTone.meanChroma,
        picks: stats.perColor.map((c) => ({
          hex: c.hex,
          ref: c.thread === undefined ? '?' : `${c.thread.brandId} ${c.thread.reference}`,
          percent: c.percent,
        })),
      };
    });

    const nonePicks = rows.find((r) => r.id === 'none')?.picks.map((p) => p.ref) ?? [];
    const withDelta = rows.map((r) => ({
      ...r,
      newPicks: r.picks.filter((p) => !nonePicks.includes(p.ref)).length,
    }));

    const jsonPath = writeReport(
      `creative-01-proto-adjust-${buildIdentity().gitSha}.json`,
      `${JSON.stringify(
        {
          schemaVersion: 1,
          startedAt: new Date().toISOString(),
          build: buildIdentity(),
          grid: GRID,
          colorLimit: COLOR_LIMIT,
          baseTone,
          candidates: withDelta,
        },
        null,
        2,
      )}\n`,
    );
    const htmlPath = writeReport('creative-01-proto-adjust-gallery.html', galleryHtml(sections));

    log.info(
      'audit',
      [
        '',
        'CREATIVE-01 adjustment-preset candidates — sample card, DMC limit 8',
        ...withDelta.map(
          (r) =>
            `  ${r.label.padEnd(17)} ΔL ${r.deltaMeanL.toFixed(1).padStart(6)}, ` +
            `Δchroma ${r.deltaMeanChroma.toFixed(1).padStart(6)}, ` +
            `${String(r.newPicks)}/${String(r.picks.length)} picks changed`,
        ),
        `  artefacts: ${jsonPath} ; ${htmlPath}`,
      ].join('\n'),
    );

    // Broken-run guards only (D139): every candidate rendered and its
    // shares add up; the None candidate changed nothing.
    for (const r of withDelta) {
      expect(r.picks.length, `${r.label} selected nothing`).toBeGreaterThan(0);
      const total = r.picks.reduce((sum, p) => sum + p.percent, 0);
      expect(total, `${r.label} shares`).toBeCloseTo(100, 1);
    }
    const none = withDelta.find((r) => r.id === 'none');
    expect(none?.deltaMeanL ?? 1).toBeCloseTo(0, 5);
    expect(none?.newPicks ?? 1).toBe(0);
  });
});

describe.runIf(!AUDIT)('CREATIVE-01 adjustment-preset candidates (skipped)', () => {
  it('gated behind AUDIT=1 — run via npm run audit', () => {
    expect(AUDIT).toBe(false);
  });
});
