/**
 * DATA-01 — sweep the thread catalogue for listings that are wrong or
 * missing, rather than surfacing them one at a time.
 *
 * Rule-shaped colour profiles read the whole catalogue, so every
 * gallery batch turned up another bad row (`ariadna:1650`,
 * `finca:4368`). Finding them a row at a time is the slowest possible
 * route to a clean list.
 *
 * **The agent's half is detection and reporting.**
 * `src/core/palettes/thread-list.csv` is protected owner data: only the
 * owner corrects it, and `catalogue.json` is then regenerated by
 * `scripts/build-palette.mjs`. Nothing here edits either.
 *
 * **This sweep reports only the two machine-CERTAIN classes** (D151's
 * split): rows with no name, and same-brand duplicate hexes. The
 * judgement classes are their own backlog items —
 * - name-versus-colour disagreement (the former DATA-02, closed as
 *   cosmetic at D188). A crude probe returns 402 hits dominated by
 *   compound names ("Blue Green", "Antique Violet") legitimately
 *   sitting between their two words. A wrong *name* is cosmetic
 *   anyway: identity is `brandId:reference` and RGB is display-only
 *   (D55/D56); real cases surface in DATA-03.
 * - **DATA-03** verification against each brand's *published* values —
 *   the class that actually affects output, blocked on owner data,
 *   since all 3,338 rows carry provenance `measured`.
 *
 * Gated behind `AUDIT=1` and deliberately **not** a gate: a failing
 * assertion over owner data the agent may not edit would block every
 * unrelated task. The two structural invariants that *are* asserted
 * (unique identity, well-formed hex) are the ones a broken generator
 * would trip, not findings about the data.
 */

import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { describe, expect, it } from 'vitest';

import { loadCatalogue } from '../../src/core/thread-catalogue.ts';
import { AUDIT, counted, publishAudit, type AuditRow } from './audit.ts';

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

const CATALOGUE = loadCatalogue();
const BRAND_NAME = new Map(CATALOGUE.brands.map((b) => [b.id, b.name]));

/** `#rrggbb`, lower-case — the shape the generator promises. */
const HEX = /^#[0-9a-f]{6}$/;

describe.skipIf(!AUDIT)('DATA-01 thread catalogue sweep (AUDIT=1)', () => {
  const rows: AuditRow[] = [];
  const findings: string[] = [];
  /** Class-2 table rows, filled by the class-2 test and read by the publisher. */
  const collisionRows: string[] = [];

  it('counts the catalogue as generated', () => {
    const perBrand = new Map<string, number>();
    for (const t of CATALOGUE.threads) {
      perBrand.set(t.brandId, (perBrand.get(t.brandId) ?? 0) + 1);
    }
    rows.push(
      counted('catalogue', {
        threads: CATALOGUE.threads.length,
        brands: CATALOGUE.brands.length,
        'distinct hexes': new Set(CATALOGUE.threads.map((t) => t.hex)).size,
        ...Object.fromEntries([...perBrand].map(([id, n]) => [id, n])),
      }),
    );
    expect(CATALOGUE.threads.length).toBeGreaterThan(0);
  });

  it('CLASS 1 — reports every row with no name at all', () => {
    const unnamed = CATALOGUE.threads.filter((t) => t.name.trim() === '');
    const perBrand = new Map<string, string[]>();
    for (const t of unnamed) {
      perBrand.set(t.brandId, [...(perBrand.get(t.brandId) ?? []), t.reference]);
    }
    rows.push(
      counted('class 1 — unnamed rows', {
        total: unnamed.length,
        brands: perBrand.size,
        ...Object.fromEntries([...perBrand].map(([id, refs]) => [id, refs.length])),
      }),
    );
    for (const [brandId, refs] of perBrand) {
      const share = ((100 * refs.length) / CATALOGUE.threads.filter((t) => t.brandId === brandId).length).toFixed(1);
      findings.push(
        `CERTAIN — ${String(refs.length)} ${BRAND_NAME.get(brandId) ?? brandId} row(s) have no name ` +
          `(${share}% of that brand). They render in the colour key as a reference with nothing ` +
          `beside it. The name column is empty in the owner CSV itself, so the generator is ` +
          `innocent. References: ${refs.join(', ')}.`,
      );
    }
    if (unnamed.length === 0) findings.push('No unnamed rows — class 1 is clean.');
    // Reported, never gated: the owner owns the CSV.
    expect(Array.isArray(unnamed)).toBe(true);
  });

  it('CLASS 2 — reports same-brand rows sharing an identical hex', () => {
    const byBrandHex = new Map<string, string[]>();
    for (const t of CATALOGUE.threads) {
      const key = `${t.brandId}|${t.hex}`;
      byBrandHex.set(key, [...(byBrandHex.get(key) ?? []), t.reference]);
    }
    const collisions = [...byBrandHex.entries()]
      .filter(([, refs]) => refs.length > 1)
      .map(([key, refs]) => {
        const [brandId = '', hex = ''] = key.split('|');
        return { brandId, hex, refs };
      })
      .sort((a, b) => a.brandId.localeCompare(b.brandId) || a.hex.localeCompare(b.hex));

    rows.push(
      counted('class 2 — same-brand identical hex', {
        groups: collisions.length,
        'rows involved': collisions.reduce((n, c) => n + c.refs.length, 0),
      }),
    );
    for (const c of collisions) {
      rows.push(
        counted(`  ${BRAND_NAME.get(c.brandId) ?? c.brandId} ${c.hex}`, {
          references: c.refs.join(' / '),
          count: c.refs.length,
        }),
      );
    }
    if (collisions.length > 0) {
      findings.push(
        `NEEDS EYES — ${String(collisions.length)} group(s) where one brand lists the same hex ` +
          `for more than one reference. Two threads sharing an RGB is normal and deliberate ` +
          `ACROSS brands (identity is brandId:reference, RGB is display-only — D55/D56, which ` +
          `is why 3,338 threads render as ${String(new Set(CATALOGUE.threads.map((t) => t.hex)).size)} ` +
          `distinct colours). Within a SINGLE brand it is likelier a transcription slip, but ` +
          `only the owner can say. Groups: ` +
          collisions.map((c) => `${c.brandId} ${c.refs.join('/')} = ${c.hex}`).join('; ') +
          '.',
      );

      // Consecutive references sharing a hex is a much stronger signal
      // than two arbitrary ones: it is the shape a copied-down cell
      // makes. Surfacing it turns "eleven groups to inspect" into a
      // ranked list.
      const adjacent = collisions.filter((c) => {
        const nums = c.refs.map((r) => Number(r)).filter((n) => Number.isFinite(n));
        if (nums.length !== c.refs.length || nums.length < 2) return false;
        const sorted = [...nums].sort((a, b) => a - b);
        return sorted.every((n, i) => i === 0 || n - (sorted[i - 1] ?? 0) === 1);
      });
      if (adjacent.length > 0) {
        findings.push(
          `RANKING HINT — ${String(adjacent.length)} of those ${String(collisions.length)} groups ` +
            `pair CONSECUTIVE references, which is the shape a copied-down spreadsheet cell ` +
            `makes rather than two threads that genuinely dye the same. Look at these first: ` +
            adjacent.map((c) => `${c.brandId} ${c.refs.join('/')} = ${c.hex}`).join('; ') +
            '.',
        );
      }
      for (const c of collisions) {
        const consecutive = adjacent.includes(c) ? '**consecutive**' : '—';
        collisionRows.push(
          `| ${BRAND_NAME.get(c.brandId) ?? c.brandId} | \`${c.hex}\` | ${c.refs.join(', ')} | ${consecutive} |`,
        );
      }
      const perBrand = new Map<string, number>();
      for (const c of collisions) perBrand.set(c.brandId, (perBrand.get(c.brandId) ?? 0) + 1);
      const worst = [...perBrand].sort((a, b) => b[1] - a[1])[0];
      if (worst !== undefined && worst[1] > 1) {
        findings.push(
          `CONCENTRATION — ${String(worst[1])} of the ${String(collisions.length)} groups are ` +
            `${BRAND_NAME.get(worst[0]) ?? worst[0]}, which points at that brand's ingest rather ` +
            `than at scattered slips — the same shape as class 1, where all ` +
            `${String(CATALOGUE.threads.filter((t) => t.name.trim() === '').length)} unnamed rows ` +
            `are one brand.`,
        );
      }
    } else {
      findings.push('No same-brand hex collisions — class 2 is clean.');
    }
    expect(Array.isArray(collisions)).toBe(true);
  });

  it('the structural invariants hold (these ARE gated)', () => {
    // Unlike the two classes above, these are not findings about the
    // owner's data — they are promises the generator makes, and a
    // breach means `build-palette.mjs` is broken.
    const ids = CATALOGUE.threads.map((t) => t.id);
    const duplicateIds = ids.filter((id, i) => ids.indexOf(id) !== i);
    const malformed = CATALOGUE.threads.filter((t) => !HEX.test(t.hex));

    rows.push(
      counted('structural', {
        'duplicate brand+reference': duplicateIds.length,
        'malformed hex': malformed.length,
      }),
    );
    expect(duplicateIds).toEqual([]);
    expect(malformed.map((t) => t.id)).toEqual([]);
  });

  it('publishes the sweep', () => {
    findings.push(
      'Out of scope here, by D151: name-versus-colour disagreement (closed as cosmetic, D188) ' +
        'and verification against published brand values (DATA-03). Re-run this sweep after each ' +
        'round of owner corrections and read the delta.',
    );
    publishAudit({
      ticket: 'DATA-01',
      question:
        'Which thread catalogue listings are certainly wrong or missing, as opposed to merely surprising?',
      rows,
      findings,
    });

    // The JSON artefact lands in `bench-reports/`, which is gitignored
    // — so the owner's actual worklist is written here as a committed
    // doc. Regenerated by `npm run audit`; never hand-edited, so the
    // delta after a round of corrections is readable in the diff.
    const unnamed = CATALOGUE.threads.filter((t) => t.name.trim() === '');
    const lines = [
      '# Thread catalogue sweep — the certain classes',
      '',
      '<!-- GENERATED by tests/audits/catalogue.audit.test.ts (npm run audit).',
      '     Do not hand-edit: re-run the sweep after corrections and commit the delta. -->',
      '',
      'Detection only (DATA-01). `src/core/palettes/thread-list.csv` is',
      'protected owner data — corrections are the owner’s, with',
      '`catalogue.json` regenerated by `scripts/build-palette.mjs`.',
      '',
      `Catalogue: **${String(CATALOGUE.threads.length)} threads** across`,
      `**${String(CATALOGUE.brands.length)} brands**, rendering as`,
      `**${String(new Set(CATALOGUE.threads.map((t) => t.hex)).size)} distinct colours**.`,
      '',
      `## Class 1 — no name at all (${String(unnamed.length)} rows)`,
      '',
      'Certain. These render in the colour key as a reference with nothing',
      'beside it. The name column is empty in the owner CSV itself.',
      '',
      '| Brand | Reference |',
      '| --- | --- |',
      ...unnamed.map((t) => `| ${BRAND_NAME.get(t.brandId) ?? t.brandId} | ${t.reference} |`),
      '',
      '## Class 2 — one brand, one hex, two references',
      '',
      'Needs eyes. Two threads sharing an RGB is normal **across** brands',
      '(identity is `brandId:reference`; RGB is display-only — D55/D56).',
      'Within a single brand it is likelier a transcription slip, but only',
      'the owner can say. Rows marked **consecutive** pair adjacent',
      'references — the shape a copied-down spreadsheet cell makes.',
      '',
      '| Brand | Hex | References | Consecutive? |',
      '| --- | --- | --- | --- |',
      ...collisionRows,
      '',
      '## Not covered here',
      '',
      '- **Name-versus-colour disagreement** — closed as cosmetic (D188): a',
      '  wrong name is ugly in the key, but identity is not the name; real',
      '  cases surface in DATA-03.',
      '- **DATA-03** — verification against each brand’s *published*',
      '  values. The class that affects output, blocked on owner data.',
    ];
    writeFileSync(join(REPO_ROOT, 'docs/catalogue-sweep.md'), `${lines.join('\n')}\n`);
    expect(rows.length).toBeGreaterThan(0);
  });
});
