/**
 * Floyd–Steinberg dither stage: golden fixture (generated by the TS
 * reference, committed) + the invariants that matter — palette
 * membership, bit-exact determinism (the bar future WASM backends
 * must clear), a hand-derived 1×4 diffusion trace, mean preservation
 * on a uniform field (the point of dithering), serpentine actually
 * changing the scan, alpha passthrough, and purity.
 */

import { describe, expect, it } from 'vitest';

import { ditherStage, type DitherParams } from '../src/core/pipeline/dither.ts';
import { resizeStage } from '../src/core/pipeline/resize.ts';
import { runPipeline } from '../src/core/pipeline/index.ts';
import { stageInstance } from '../src/core/types.ts';
import type { Palette, PixelBuffer } from '../src/core/types.ts';
import { expectBufferMatch, loadGolden } from './helpers/golden.ts';

const TEST_PALETTE: Palette = {
  name: 'test-rwbk',
  entries: [
    { code: 'R', name: 'red', hex: '#ff0000', rgb: [255, 0, 0], manufacturer: 'test' },
    { code: 'W', name: 'white', hex: '#ffffff', rgb: [255, 255, 255], manufacturer: 'test' },
    { code: 'B', name: 'blue', hex: '#0000ff', rgb: [0, 0, 255], manufacturer: 'test' },
    { code: 'K', name: 'black', hex: '#000000', rgb: [0, 0, 0], manufacturer: 'test' },
  ],
};

const BW_PALETTE: Palette = {
  name: 'test-bw',
  entries: [
    { code: 'K', name: 'black', hex: '#000000', rgb: [0, 0, 0], manufacturer: 'test' },
    { code: 'W', name: 'white', hex: '#ffffff', rgb: [255, 255, 255], manufacturer: 'test' },
  ],
};

function params(overrides: Partial<DitherParams> = {}): DitherParams {
  return { palette: TEST_PALETTE, metric: 'rgb', serpentine: true, ...overrides };
}

function grayField(width: number, height: number, level: number): PixelBuffer {
  const data = new Uint8ClampedArray(width * height * 4);
  for (let i = 0; i < width * height; i++) {
    data[i * 4] = level;
    data[i * 4 + 1] = level;
    data[i * 4 + 2] = level;
    data[i * 4 + 3] = 255;
  }
  return { width, height, data };
}

describe('Floyd–Steinberg dither stage', () => {
  it('matches the committed golden fixture bit-exactly (tolerance 0)', () => {
    const input = loadGolden('dither-8x8.input');
    const output = runPipeline(input, [stageInstance(ditherStage, params())]);
    expectBufferMatch(output, loadGolden('dither-8x8.expected'), 0);
  });

  it('reproduces the hand-derived 1x4 diffusion trace (gray 128, B/W)', () => {
    // work=128 → white (err −127); 72.44 → black (err +72.44);
    // 159.69 → white (err −95.31); 86.30 → black. See D14.
    const input = grayField(4, 1, 128);
    const output = runPipeline(input, [
      stageInstance(ditherStage, params({ palette: BW_PALETTE })),
    ]);
    const levels = [0, 1, 2, 3].map((x) => output.data[x * 4]);
    expect(levels).toEqual([255, 0, 255, 0]);
  });

  it('every output pixel is a palette colour', () => {
    const input = loadGolden('dither-8x8.input');
    const allowed = new Set(TEST_PALETTE.entries.map((e) => e.rgb.join(',')));
    const output = runPipeline(input, [stageInstance(ditherStage, params())]);
    for (let i = 0; i < output.data.length; i += 4) {
      const key = `${String(output.data[i])},${String(output.data[i + 1])},${String(output.data[i + 2])}`;
      expect(allowed.has(key), `pixel ${String(i / 4)} → ${key}`).toBe(true);
    }
  });

  it('is bit-exact deterministic across runs and metrics', () => {
    const input = loadGolden('dither-8x8.input');
    for (const metric of ['rgb', 'lab'] as const) {
      const a = runPipeline(input, [stageInstance(ditherStage, params({ metric }))]);
      const b = runPipeline(input, [stageInstance(ditherStage, params({ metric }))]);
      expectBufferMatch(a, b, 0);
    }
  });

  it('preserves mean level on a uniform field (the point of dithering)', () => {
    // 32×32 gray 100 against B/W: the dithered mean must sit near 100
    // — quantising without diffusion would land on 0 or 255.
    const input = grayField(32, 32, 100);
    const output = runPipeline(input, [
      stageInstance(ditherStage, params({ palette: BW_PALETTE })),
    ]);
    let sum = 0;
    for (let i = 0; i < output.data.length; i += 4) sum += output.data[i] ?? 0;
    const mean = sum / (32 * 32);
    // Edge pixels lose diffused error, so allow a small bias.
    expect(Math.abs(mean - 100)).toBeLessThanOrEqual(3);
  });

  it('serpentine changes the scan (differs from raster on a gradient)', () => {
    const input = loadGolden('dither-8x8.input');
    const serp = runPipeline(input, [stageInstance(ditherStage, params())]);
    const raster = runPipeline(input, [
      stageInstance(ditherStage, params({ serpentine: false })),
    ]);
    let differs = false;
    for (let i = 0; i < serp.data.length && !differs; i++) {
      differs = serp.data[i] !== raster.data[i];
    }
    expect(differs).toBe(true);
  });

  it('passes alpha through and never mutates its input', () => {
    const input = loadGolden('dither-8x8.input');
    input.data[3] = 129; // one non-opaque alpha to carry through
    const before = Array.from(input.data);
    const output = runPipeline(input, [stageInstance(ditherStage, params())]);
    expect(Array.from(input.data)).toEqual(before);
    for (let i = 3; i < input.data.length; i += 4) {
      expect(output.data[i]).toBe(input.data[i]);
    }
  });
});

/**
 * Regression (M5-ACCEPT-01). Empty cells used to be quantised as if
 * they were opaque black and diffused THAT error into the stitches
 * beside them, so a `contain`/`fit` letterbox band destroyed the
 * dither of the artwork it framed. The palette below is the adversarial
 * case — nothing near black, so the phantom error was the full
 * distance to the darkest thread.
 */
describe('empty cells take no part in error diffusion', () => {
  const LIGHT_PALETTE: Palette = {
    name: 'test-light',
    entries: [
      { code: 'L', name: 'light', hex: '#c8c8c8', rgb: [200, 200, 200], manufacturer: 'test' },
      { code: 'W', name: 'white', hex: '#ffffff', rgb: [255, 255, 255], manufacturer: 'test' },
    ],
  };

  /** `count` fully transparent cells, then `width - count` of `level`. */
  function paddedRow(width: number, count: number, level: number): PixelBuffer {
    const data = new Uint8ClampedArray(width * 4);
    for (let x = count; x < width; x++) {
      data[x * 4] = level;
      data[x * 4 + 1] = level;
      data[x * 4 + 2] = level;
      data[x * 4 + 3] = 255;
    }
    return { width, height: 1, data };
  }

  const p = params({ palette: LIGHT_PALETTE, metric: 'lab', serpentine: false });

  it('leaves an empty cell empty rather than giving it a thread colour', () => {
    const output = runPipeline(paddedRow(8, 2, 220), [stageInstance(ditherStage, p)]);
    expect(Array.from(output.data.slice(0, 8))).toEqual([0, 0, 0, 0, 0, 0, 0, 0]);
  });

  it('dithers stitches identically whether or not empty cells precede them', () => {
    const padded = runPipeline(paddedRow(8, 2, 220), [stageInstance(ditherStage, p)]);
    const isolated = runPipeline(paddedRow(6, 0, 220), [stageInstance(ditherStage, p)]);
    expect(Array.from(padded.data.slice(8))).toEqual(Array.from(isolated.data));
  });

  it('preserves mean level across a letterbox band (the defect it closes)', () => {
    // 2:1 source into a square grid: `contain` leaves empty bands top
    // and bottom. Before the fix this dithered to solid 200 — no
    // dithering at all, and a mean 20 levels below the source.
    const source = grayField(16, 8, 220);
    const grid = runPipeline(source, [
      stageInstance(resizeStage, { width: 8, height: 8, mode: 'contain' }),
      stageInstance(ditherStage, p),
    ]);

    let sum = 0;
    let stitches = 0;
    for (let i = 0; i < grid.data.length; i += 4) {
      if (grid.data[i + 3] === 0) continue;
      sum += grid.data[i] ?? 0;
      stitches++;
    }
    expect(stitches).toBe(32); // 8×4 opaque band, 8×2 empty top and bottom
    expect(Math.abs(sum / stitches - 220)).toBeLessThan(4);
  });
});
