/**
 * M14 UI-baseline byte-identity tripwire (M14-AUDIT-01 → M14-VERIFY-02).
 *
 * M14 is a UI-only milestone: engine, worker and export outputs must
 * stay byte-identical throughout (D73). This test pins the reference
 * behaviour at audit time so every later M14 task re-proves it by
 * running `check`:
 *
 * - the committed fixture PNG (the source the browser-side export
 *   captures import) is byte-stable;
 * - the reference pipeline output (pixels + palette-index sidecar) for
 *   the app-default configuration over that source is byte-stable;
 * - the serialized default project file is byte-stable (schema and
 *   field order — the browser-saved file differs only in the
 *   viewport-derived `preview.cssPxPerStitch`, compared field-wise in
 *   M14-VERIFY-02, not by hash).
 *
 * Bootstrap: on first run the committed artefacts
 * (`source-gradient-256.png`, `hashes.json`) are written if absent —
 * they are committed with this test and never regenerated by CI. A
 * hash mismatch after that means engine-visible behaviour changed
 * inside a UI-only milestone: that is a defect, never a fixture to
 * refresh.
 */

import { createHash } from 'node:crypto';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { describe, expect, it } from 'vitest';

import { DEFAULT_GRID_VALUES } from '../../src/core/grid-style.ts';
import { DEFAULT_DITHER, type PipelineConfig } from '../../src/core/pipeline/config.ts';
import { type PalettePolicy } from '../../src/core/palette-policy.ts';
import { resolveProjectPalette } from '../../src/core/palette-resolve.ts';
import { loadCatalogue } from '../../src/core/thread-catalogue.ts';
import {
  SCHEMA_VERSION,
  serializeProject,
  type ProjectFile,
} from '../../src/core/project.ts';
import { SYMBOL_IDS } from '../../src/core/symbols/glyphs.ts';
import { executeRequest } from '../../src/worker/execute.ts';
import { encodePng, sourceBuffer, SOURCE_SIDE } from './source.ts';

const here = dirname(fileURLToPath(import.meta.url));
const pngPath = join(here, 'source-gradient-256.png');
const hashesPath = join(here, 'hashes.json');

function sha256(bytes: Uint8Array): string {
  return createHash('sha256').update(bytes).digest('hex');
}

/**
 * The audit-time reference policy, frozen inline. This tripwire pins
 * *engine* behaviour over a fixed configuration; it deliberately does
 * not read `defaultPolicy()`, whose fresh-session default is a UI
 * policy decision that changed at M14-EXT-13 (D98: at-most-8,
 * superseding D55's unlimited) — a default change is not engine
 * drift, and coupling the pin to it would make the tripwire fire on
 * intended taste decisions instead of defects. Engine identity stays
 * proven by these hashes exactly as at audit time.
 */
function auditTimePolicy(): PalettePolicy {
  return {
    brands: ['dmc'],
    source: { kind: 'brands' },
    ownedOnly: false,
    count: { mode: 'all', n: 20 },
    locked: [],
    preferred: [],
    excluded: [],
  };
}

/** The audit-time pipeline config over the reference resolved palette. */
function defaultConfig(): PipelineConfig {
  const catalogue = loadCatalogue();
  const resolved = resolveProjectPalette({
    policy: auditTimePolicy(),
    inputs: { catalogue, owned: new Set<string>() },
    name: 'DMC',
  });
  if (!resolved.ok) throw new Error('reference policy did not resolve');
  return {
    preset: 'resize-first',
    grid: { width: 200, height: 200 },
    resizeMode: 'contain',
    palette: resolved.palette,
    metric: 'lab',
    dither: { ...DEFAULT_DITHER },
  };
}

/** The stated default project file (preview pinned at 1 CSS px/stitch). */
function defaultProject(config: PipelineConfig): ProjectFile {
  return {
    schemaVersion: SCHEMA_VERSION,
    pipeline: {
      preset: config.preset,
      grid: { ...config.grid },
      resizeMode: config.resizeMode,
      metric: config.metric,
      dither: config.dither,
      // The default no-dither config structurally matches the "None"
      // built-in (D117's dissolved legacy state), so the stated
      // default carries its reference.
      ditherProfileRef: { id: 'builtin:none', revision: 0 },
    },
    palette: {
      profileRef: { id: 'builtin:dmc', revision: 0 },
      recipe: { libraries: ['dmc'], ownedOnly: false, include: [], exclude: [], ranges: [] },
      design: { count: { mode: 'max', n: 8 }, minDistance: 0, mustUse: [] },
      snapshot: config.palette?.entries ?? [],
    },
    // Schema v7 (M11): screen + print halves, both at the defaults a
    // fresh session holds — which byte-match the Every 10 preset, so
    // that is the honest provenance (the projectJson pin moved for
    // the bump; the engine hashes never move).
    gridStyle: {
      screen: { ...DEFAULT_GRID_VALUES },
      print: { ...DEFAULT_GRID_VALUES },
      preset: 'every-10',
    },
    // A fresh session has granted nothing: the full catalogue queued in
    // canonical order, exactly as `initialSymbolState` builds it
    // (schema v6, M9 — the projectJson pin was refreshed for the bump;
    // the engine hashes above never moved).
    symbols: { assigned: [], queue: [...SYMBOL_IDS], overrides: [] },
    preview: { mode: 'space', cssPxPerStitch: 1 },
    export: {
      scale: 1,
      background: 'transparent',
      color: '#ffffff',
      chartCell: 10,
      chartMode: 'color',
      pdf: {
        pageSize: 'a4',
        orientation: 'portrait',
        marginMm: 15,
        title: '',
        // Schema v8 (M10): one fitted page stays the default.
        pages: 'single',
        stitchesPerPage: 60,
        overlapStitches: 2,
      },
    },
    // Schema v9 (M12): the documented default estimation model.
    estimates: {
      fabricCount: 14,
      marginCm: 5,
      strands: 2,
      routingFactor: 1.2,
      wasteShare: 0.1,
      skeinMetres: 8,
    },
  };
}

interface BaselineHashes {
  sourcePng: string;
  outputPixels: string;
  outputIndices: string;
  projectJson: string;
}

describe('M14 UI baseline (byte-identity tripwire)', () => {
  const source = sourceBuffer();

  it('pins the committed fixture PNG', () => {
    if (!existsSync(pngPath)) writeFileSync(pngPath, encodePng(source));
    const committed = new Uint8Array(readFileSync(pngPath));
    const expected = readHashes()?.sourcePng;
    expect(sha256(committed)).toBe(expected ?? sha256(committed));
    ensureHashes({ sourcePng: sha256(committed) });
  });

  it('pins the reference pipeline output for the default config', () => {
    const config = defaultConfig();
    const pixels = new Uint8ClampedArray(source.data); // keep the fixture pristine
    const response = executeRequest(
      {
        type: 'process',
        id: 1,
        width: SOURCE_SIDE,
        height: SOURCE_SIDE,
        pixels: pixels.buffer,
        config,
        // Pure reference baseline: the TS backend for every stage, so
        // the pin is independent of wasm/webgpu availability.
        force: { resize: 'ts', reduce: 'ts', dither: 'ts' },
      },
      () => 0,
    );
    if (response.type !== 'result') throw new Error(`pipeline failed: ${response.type}`);
    expect(response.width).toBe(200);
    expect(response.height).toBe(200);
    for (const timing of response.timings) expect(timing.backend).toBe('ts');
    const pixelHash = sha256(new Uint8Array(response.pixels));
    expect(response.indices).not.toBeNull();
    const indexHash = sha256(new Uint8Array(response.indices ?? new ArrayBuffer(0)));
    const expected = readHashes();
    expect(pixelHash).toBe(expected?.outputPixels ?? pixelHash);
    expect(indexHash).toBe(expected?.outputIndices ?? indexHash);
    ensureHashes({ outputPixels: pixelHash, outputIndices: indexHash });
  });

  it('pins the serialized default project file', () => {
    const json = serializeProject(defaultProject(defaultConfig()));
    const hash = sha256(new TextEncoder().encode(json));
    const expected = readHashes()?.projectJson;
    expect(hash).toBe(expected ?? hash);
    ensureHashes({ projectJson: hash });
  });
});

function readHashes(): Partial<BaselineHashes> | null {
  if (!existsSync(hashesPath)) return null;
  return JSON.parse(readFileSync(hashesPath, 'utf8')) as Partial<BaselineHashes>;
}

/** Merge newly computed hashes in; only ever fills gaps (bootstrap). */
function ensureHashes(update: Partial<BaselineHashes>): void {
  const current = readHashes() ?? {};
  const merged = { ...update, ...current };
  const next = `${JSON.stringify(merged, null, 2)}\n`;
  // Write only on change: an unconditional write fires a file-watch
  // event on every test run, which full-reloads a dev server open on
  // the same root mid-session.
  if (existsSync(hashesPath) && readFileSync(hashesPath, 'utf8') === next) return;
  writeFileSync(hashesPath, next);
}
