/**
 * M14 UI-baseline fixture source (M14-AUDIT-01).
 *
 * One deterministic 256×256 RGBA source, generated from stated
 * constants, that the M14 byte-identity proof runs on: the committed
 * PNG (`source-gradient-256.png`) is imported through the app UI for
 * the browser-side export captures, and `baseline.test.ts` runs the
 * same buffer through the reference pipeline in node. M14 is UI-only,
 * so these outputs must not change for the life of the milestone
 * (D73); the test is the tripwire.
 *
 * Content: a two-axis colour gradient with seeded LCG noise (±15 per
 * channel) and a flat 64×64 centre block — gradient for dither
 * behaviour, noise so no region is accidentally uniform, a flat block
 * so palette mapping has a stable area. Fully opaque.
 *
 * The PNG encoder is minimal and write-once: the committed PNG is
 * never regenerated by CI (zlib output can differ across Node
 * releases); `baseline.test.ts` asserts the committed file's hash
 * instead of re-encoding.
 */

import { deflateSync } from 'node:zlib';

import type { PixelBuffer } from '../../src/core/types.ts';

/** Fixture edge length, px. */
export const SOURCE_SIDE = 256;

/** LCG seed — stated so the buffer is reproducible from this file. */
export const SOURCE_SEED = 0x9e3779b9;

/** Numerical Recipes LCG; 32-bit, deterministic across platforms. */
function lcg(state: number): number {
  return (Math.imul(state, 1664525) + 1013904223) >>> 0;
}

/** Build the deterministic source buffer (same bytes every call). */
export function sourceBuffer(): PixelBuffer {
  const side = SOURCE_SIDE;
  const data = new Uint8ClampedArray(side * side * 4);
  let state = SOURCE_SEED;
  const flatMin = side / 2 - 32;
  const flatMax = side / 2 + 32;
  for (let y = 0; y < side; y++) {
    for (let x = 0; x < side; x++) {
      const i = (y * side + x) * 4;
      const flat = x >= flatMin && x < flatMax && y >= flatMin && y < flatMax;
      state = lcg(state);
      // One draw per pixel even in the flat block, so the noise field
      // (and every pixel after it) does not depend on the block bounds.
      const noise = flat ? 0 : ((state >>> 8) % 31) - 15;
      if (flat) {
        data[i] = 178;
        data[i + 1] = 34;
        data[i + 2] = 34;
      } else {
        data[i] = Math.min(255, Math.max(0, Math.round((x / (side - 1)) * 255) + noise));
        data[i + 1] = Math.min(255, Math.max(0, Math.round((y / (side - 1)) * 255) + noise));
        data[i + 2] = Math.min(255, Math.max(0, 128 + noise));
      }
      data[i + 3] = 255;
    }
  }
  return { width: side, height: side, data };
}

/** CRC-32 (PNG chunk checksum), standard polynomial. */
function crc32(bytes: Uint8Array): number {
  let crc = 0xffffffff;
  for (const byte of bytes) {
    crc ^= byte;
    for (let bit = 0; bit < 8; bit++) {
      crc = (crc >>> 1) ^ (0xedb88320 & -(crc & 1));
    }
  }
  return (crc ^ 0xffffffff) >>> 0;
}

function chunk(type: string, body: Uint8Array): Uint8Array {
  const out = new Uint8Array(12 + body.length);
  const view = new DataView(out.buffer);
  view.setUint32(0, body.length);
  for (let i = 0; i < 4; i++) out[4 + i] = type.charCodeAt(i);
  out.set(body, 8);
  view.setUint32(8 + body.length, crc32(out.subarray(4, 8 + body.length)));
  return out;
}

/** Encode an RGBA buffer as an 8-bit truecolour+alpha PNG. */
export function encodePng(buffer: PixelBuffer): Uint8Array {
  const { width, height, data } = buffer;
  const ihdr = new Uint8Array(13);
  const ihdrView = new DataView(ihdr.buffer);
  ihdrView.setUint32(0, width);
  ihdrView.setUint32(4, height);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: truecolour + alpha
  // Raw scanlines, filter byte 0 per row.
  const raw = new Uint8Array(height * (1 + width * 4));
  for (let y = 0; y < height; y++) {
    raw.set(data.subarray(y * width * 4, (y + 1) * width * 4), y * (1 + width * 4) + 1);
  }
  const idat = deflateSync(raw, { level: 9 });
  const signature = new Uint8Array([137, 80, 78, 71, 13, 10, 26, 10]);
  const parts = [
    signature,
    chunk('IHDR', ihdr),
    chunk('IDAT', new Uint8Array(idat)),
    chunk('IEND', new Uint8Array(0)),
  ];
  const total = parts.reduce((sum, p) => sum + p.length, 0);
  const out = new Uint8Array(total);
  let offset = 0;
  for (const part of parts) {
    out.set(part, offset);
    offset += part.length;
  }
  return out;
}
