/**
 * Golden-fixture harness (conventions.md → "Testing").
 *
 * Fixtures live in tests/golden/ as JSON PixelBuffers, generated by
 * the TS reference and committed. They are protected files:
 * regenerating one needs owner approval with a stated reason — never
 * to make a failing test pass.
 */

import { readFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { expect } from 'vitest';

import type { PixelBuffer } from '../../src/core/types.ts';

const GOLDEN_DIR = join(dirname(fileURLToPath(import.meta.url)), '..', 'golden');

/** JSON shape of a committed fixture. */
interface FixtureFile {
  width: number;
  height: number;
  data: number[];
}

/** Load a committed fixture (e.g. "hello-4x4.input") as a PixelBuffer. */
export function loadGolden(name: string): PixelBuffer {
  const raw = readFileSync(join(GOLDEN_DIR, `${name}.json`), 'utf8');
  const parsed = JSON.parse(raw) as FixtureFile;
  const buffer: PixelBuffer = {
    width: parsed.width,
    height: parsed.height,
    data: new Uint8ClampedArray(parsed.data),
  };
  expectValidBuffer(buffer, name);
  return buffer;
}

/** Assert the RGBA length invariant holds (data.length = w*h*4). */
export function expectValidBuffer(buffer: PixelBuffer, label = 'buffer'): void {
  expect(
    buffer.data.length,
    `${label}: data.length must equal width*height*4`,
  ).toBe(buffer.width * buffer.height * 4);
}

/**
 * Compare two buffers channel-by-channel.
 *
 * `tolerance` is the per-channel absolute difference allowed (0–255
 * scale): 0 for deterministic stages (error diffusion is bit-exact),
 * a small documented value for GPU float math (≤ 1/255 per channel —
 * pass 1). Each test states its own tolerance.
 */
export function expectBufferMatch(
  actual: PixelBuffer,
  expected: PixelBuffer,
  tolerance = 0,
): void {
  expect(actual.width, 'width').toBe(expected.width);
  expect(actual.height, 'height').toBe(expected.height);
  expectValidBuffer(actual, 'actual');
  expectValidBuffer(expected, 'expected');

  for (let i = 0; i < expected.data.length; i++) {
    const a = actual.data[i] ?? 0;
    const e = expected.data[i] ?? 0;
    const diff = Math.abs(a - e);
    if (diff > tolerance) {
      const pixel = Math.floor(i / 4);
      const x = pixel % expected.width;
      const y = Math.floor(pixel / expected.width);
      const channel = 'RGBA'[i % 4] ?? '?';
      expect.fail(
        `channel ${channel} at (${String(x)}, ${String(y)}) differs by ` +
          `${String(diff)} (actual ${String(a)}, expected ${String(e)}, ` +
          `tolerance ${String(tolerance)})`,
      );
    }
  }
}
